packages = {1: {"Address":"195 W Oakland Ave", "City":"Salt Lake City", "Zip":"84115", "Delivery_Deadline":"10:30", "Weight":"21"},
            2: {"Address":"2530 S 500 E", "City":"Salt Lake City", "Zip":"84106", "Delivery_Deadline":"EOD", "Weight":"44"},
            3: {"Address":"233 Canyon Rd", "City":"Salt Lake City", "Zip":"84103", "Delivery_Deadline":"EOD", "Weight":"2", "Truck":2},
            4: {"Address":"380 W 2880 S", "City":"Salt Lake City", "Zip":"84115", "Delivery_Deadline":"EOD", "Weight":"4"},
            5: {"Address":"410 S State St", "City":"Salt Lake City", "Zip":"84111", "Delivery_Deadline":"EOD", "Weight":"5"},
            6: {"Address":"3060 Lester St", "City":"West Valley City", "Zip":"84119", "Delivery_Deadline":"10:30", "Weight":"88", "Available":"9:05"},
            7: {"Address":"1330 2100 S", "City":"Salt Lake City", "Zip":"84106", "Delivery_Deadline":"EOD", "Weight":"8"},
            8: {"Address":"300 State St", "City":"Salt Lake City", "Zip":"84103", "Delivery_Deadline":"EOD", "Weight":"9"},
            9: {"Address":"300 State St", "City":"Salt Lake City", "Zip":"84103", "Delivery_Deadline":"EOD", "Weight":"2"},
            10: {"Address":"600 E 900 South", "City":"Salt Lake City", "Zip":"84105", "Delivery_Deadline":"EOD", "Weight":"1"},
            11: {"Address":"2600 Taylorsville Blvd", "City":"Salt Lake City", "Zip":"84118", "Delivery_Deadline":"EOD", "Weight":"1"},
            12: {"Address":"3575 W Valley Central Station bus Loop", "City":"West Valley City", "Zip":"84119", "Delivery_Deadline":"EOD", "Weight":"1"},
            13: {"Address":"2010 W 500 S", "City":"Salt Lake City", "Zip":"84104", "Delivery_Deadline":"10:30", "Weight":"2"},
            14: {"Address":"4300 S 1300 E", "City":"Millcreek", "Zip":"84117", "Delivery_Deadline":"10:30", "Weight":"88", "Packaged With":[15,19]},
            15: {"Address":"4580 S 2300 E", "City":"Holladay", "Zip":"84117", "Delivery_Deadline":"9:00", "Weight":"4"},
            16: {"Address":"4580 S 2300 E", "City":"Holladay", "Zip":"84117", "Delivery_Deadline":"10:30", "Weight":"88", "Packaged With":[13,19]},
            17: {"Address":"3148 S 1100 W", "City":"Salt Lake City", "Zip":"84119", "Delivery_Deadline":"EOD", "Weight":"2"},
            18: {"Address":"1488 4800 S", "City":"Salt Lake City", "Zip":"84123", "Delivery_Deadline":"EOD", "Weight":"6", "Truck":2},
            19: {"Address":"177 W Price Ave", "City":"Salt Lake City", "Zip":"84115", "Delivery_Deadline":"EOD", "Weight":"37"},
            20: {"Address":"3595 Main St", "City":"Salt Lake City", "Zip":"84115", "Delivery_Deadline":"10:30", "Weight":"37", "Packaged With":[13,15]},
            21: {"Address":"3595 Main St", "City":"Salt Lake City", "Zip":"84115", "Delivery_Deadline":"EOD", "Weight":"3"},
            22: {"Address":"6351 South 900 East", "City":"Murray", "Zip":"84121", "Delivery_Deadline":"EOD", "Weight":"2"},
            23: {"Address":"5100 South 2700 West", "City":"Salt Lake City", "Zip":"84118", "Delivery_Deadline":"EOD", "Weight":"5"},
            24: {"Address":"5025 State St", "City":"Murray", "Zip":"84107", "Delivery_Deadline":"EOD", "Weight":"7"},
            25: {"Address":"5383 South 900 East #104", "City":"Salt Lake City", "Zip":"84117", "Delivery_Deadline":"10:30", "Weight":"7", "Available":"9:05"},
            26: {"Address":"5383 South 900 East #104", "City":"Salt Lake City", "Zip":"84117", "Delivery_Deadline":"EOD", "Weight":"25"},
            27: {"Address":"1060 Dalton Ave S", "City":"Salt Lake City", "Zip":"84104", "Delivery_Deadline":"EOD", "Weight":"5"},
            28: {"Address":"2835 Main St", "City":"Salt Lake City", "Zip":"84115", "Delivery_Deadline":"EOD", "Weight":"7", "Available":"9:05"},
            29: {"Address":"1330 2100 S", "City":"Salt Lake City", "Zip":"84106", "Delivery_Deadline":"10:30", "Weight":"2"},
            30: {"Address":"300 State St", "City":"Salt Lake City", "Zip":"84103", "Delivery_Deadline":"10:30", "Weight":"1"},
            31: {"Address":"3365 S 900 W", "City":"Salt Lake City", "Zip":"84119", "Delivery_Deadline":"10:30", "Weight":"1"},
            32: {"Address":"3365 S 900 W", "City":"Salt Lake City", "Zip":"84119", "Delivery_Deadline":"EOD", "Weight":"1", "Available":"9:05"},
            33: {"Address":"2530 S 500 E", "City":"Salt Lake City", "Zip":"84106", "Delivery_Deadline":"EOD", "Weight":"1"},
            34: {"Address":"4580 S 2300 E", "City":"Holladay", "Zip":"84117", "Delivery_Deadline":"10:30", "Weight":"2"},
            35: {"Address":"1060 Dalton Ave S", "City":"Salt Lake City", "Zip":"84104", "Delivery_Deadline":"EOD", "Weight":"88"},
            36: {"Address":"2300 Parkway Blvd", "City":"West Valley City", "Zip":"84119", "Delivery_Deadline":"EOD", "Weight":"88", "Truck":2},
            37: {"Address":"410 S State St", "City":"Salt Lake City", "Zip":"84111", "Delivery_Deadline":"10:30", "Weight":"2"},
            38: {"Address":"410 S State St", "City":"Salt Lake City", "Zip":"84111", "Delivery_Deadline":"EOD", "Weight":"9", "Truck":2},
            39: {"Address":"2010 W 500 S", "City":"Salt Lake City", "Zip":"84104", "Delivery_Deadline":"EOD", "Weight":"9"},
            40: {"Address":"380 W 2880 S", "City":"Salt Lake City", "Zip":"84115", "Delivery_Deadline":"10:30", "Weight":"45"}
            }


class Distances:

    def __init__(self):
        self.distances = {"HUB" : {"HUB" : 0,
                                   "International Peace Gardens" : 7.2,
                                   "Sugar House Park" : 3.8,
                                   "Taylorsville-Bennion Heritage City Gov Off" : 11,
                                   "Salt Lake City Division of Health Services" : 2.2,
                                   "South Salt Lake Public Works" : 3.5,
                                   "Salt Lake City Streets and Sanitation" : 10.9,
                                   "Deker Lake" : 8.6,
                                   "Salt Lake City Ottinger Hall" :  7.6,
                                   "Columbus Library" : 2.8,
                                   "Taylorsville City Hall" : 6.4,
                                   "South Salt Lake Police" : 3.2,
                                   "Council Hall" : 7.6,
                                   "Redwood Park" : 5.2,
                                   "Salt Lake County Mental Health" : 4.4,
                                   "Salt Lake County/United Police Dept" : 3.7,
                                   "West Valley Prosecutor" : 7.6,
                                   "Housing Auth. of Salt Lake County" : 2.0,
                                   "Utah DMV Administrative Office" : 3.6,
                                   "Third District Juvenile Court" : 6.5,
                                   "Cottonwood Regional Softball Complex" : 1.9,
                                   "Holiday City Office" : 3.4,
                                   "Murray City Museum" : 2.4,
                                   "Valley Regional Softball Complex" : 6.4,
                                   "City Center of Rock Springs" : 2.4,
                                   "Rice Terrace Pavilion Park" : 5.0,
                                   "Wheeler Historic Farm" : 3.6
                                   },
                            "International Peace Gardens" : {"HUB" : 7.2, "International Peace Gardens" : 0, "Sugar House Park" : 7.1,
                                                            "Taylorsville-Bennion Heritage City Gov Off" : 6.4,
                                                            "Salt Lake City Division of Health Services" : 6,
                                                            "South Salt Lake Public Works" : 4.8,
                                                            "Salt Lake City Streets and Sanitation" : 1.6,
                                                            "Deker Lake" : 2.8,
                                                            "Salt Lake City Ottinger Hall" : 4.8,
                                                            "Columbus Library" : 6.3,
                                                            "Taylorsville City Hall" : 7.3,
                                                            "South Salt Lake Police" : 5.3,
                                                            "Council Hall" : 4.8,
                                                            "Redwood Park" : 3,
                                                            "Salt Lake County Mental Health" : 4.6,
                                                            "Salt Lake County/United Police Dept" : 4.5,
                                                            "West Valley Prosecutor" : 7.4,
                                                            "Housing Auth. of Salt Lake County" : 6,
                                                            "Utah DMV Administrative Office" : 5,
                                                            "Third District Juvenile Court" : 4.8,
                                                            "Cottonwood Regional Softball Complex" : 9.5,
                                                            "Holiday City Office" : 10.9,
                                                            "Murray City Museum" : 8.3,
                                                            "Valley Regional Softball Complex" : 6.9,
                                                            "City Center of Rock Springs" : 10,
                                                            "Rice Terrace Pavilion Park" : 4.4,
                                                            "Wheeler Historic Farm" : 13
                                                            },
                            'Sugar House Park': {'HUB': 3.8,
                                                 'International Peace Gardens': 7.1,
                                                 'Sugar House Park': 0.0,
                                                 'Taylorsville-Bennion Heritage City Gov Off': 9.2,
                                                 'Salt Lake City Division of Health Services': 4.4,
                                                 'South Salt Lake Public Works': 2.8,
                                                 'Salt Lake City Streets and Sanitation': 8.6,
                                                 'Deker Lake': 6.3,
                                                 'Salt Lake City Ottinger Hall': 5.3,
                                                 'Columbus Library': 1.6,
                                                 'Taylorsville City Hall': 10.4,
                                                 'South Salt Lake Police': 3.0,
                                                 'Council Hall': 5.3,
                                                 'Redwood Park': 6.5,
                                                 'Salt Lake County Mental Health': 5.6,
                                                 'Salt Lake County/United Police Dept': 5.8,
                                                 'West Valley Prosecutor': 5.7,
                                                 'Housing Auth. of Salt Lake County': 4.1,
                                                 'Utah DMV Administrative Office': 3.6,
                                                 'Third District Juvenile Court': 4.3,
                                                 'Cottonwood Regional Softball Complex': 3.3,
                                                 'Holiday City Office': 5.0,
                                                 'Murray City Museum': 6.1,
                                                 'Valley Regional Softball Complex': 9.7,
                                                 'City Center of Rock Springs': 6.1,
                                                 'Rice Terrace Pavilion Park': 2.8,
                                                 'Wheeler Historic Farm': 7.4},
                            'Taylorsville-Bennion Heritage City Gov Off': {'HUB': 11.0,
                                                                           'International Peace Gardens': 6.4,
                                                                           'Sugar House Park': 9.2,
                                                                           'Taylorsville-Bennion Heritage City Gov Off': 0.0,
                                                                           'Salt Lake City Division of Health Services': 5.6,
                                                                           'South Salt Lake Public Works': 6.9,
                                                                           'Salt Lake City Streets and Sanitation': 8.6,
                                                                           'Deker Lake': 4.0,
                                                                           'Salt Lake City Ottinger Hall': 11.1,
                                                                           'Columbus Library': 7.3,
                                                                           'Taylorsville City Hall': 1.0,
                                                                           'South Salt Lake Police': 6.4,
                                                                           'Council Hall': 11.1,
                                                                           'Redwood Park': 3.9,
                                                                           'Salt Lake County Mental Health': 4.3,
                                                                           'Salt Lake County/United Police Dept': 4.4,
                                                                           'West Valley Prosecutor': 7.2,
                                                                           'Housing Auth. of Salt Lake County': 5.3,
                                                                           'Utah DMV Administrative Office': 6.0,
                                                                           'Third District Juvenile Court': 10.6,
                                                                           'Cottonwood Regional Softball Complex': 5.9,
                                                                           'Holiday City Office': 7.4,
                                                                           'Murray City Museum': 4.7,
                                                                           'Valley Regional Softball Complex': 0.6,
                                                                           'City Center of Rock Springs': 6.4,
                                                                           'Rice Terrace Pavilion Park': 10.1,
                                                                           'Wheeler Historic Farm': 10.1},
                            'Salt Lake City Division of Health Services': {'HUB': 2.2,
                                                                            'International Peace Gardens': 6.0,
                                                                            'Sugar House Park': 4.4,
                                                                            'Taylorsville-Bennion Heritage City Gov Off': 5.6,
                                                                            'Salt Lake City Division of Health Services': 0.0,
                                                                            'South Salt Lake Public Works': 1.9,
                                                                            'Salt Lake City Streets and Sanitation': 7.9,
                                                                            'Deker Lake': 5.1,
                                                                            'Salt Lake City Ottinger Hall': 7.5,
                                                                            'Columbus Library': 2.6,
                                                                            'Taylorsville City Hall': 6.5,
                                                                            'South Salt Lake Police': 1.5,
                                                                            'Council Hall': 7.5,
                                                                            'Redwood Park': 3.2,
                                                                            'Salt Lake County Mental Health': 2.4,
                                                                            'Salt Lake County/United Police Dept': 2.7,
                                                                            'West Valley Prosecutor': 1.4,
                                                                            'Housing Auth. of Salt Lake County': 0.5,
                                                                            'Utah DMV Administrative Office': 1.7,
                                                                            'Third District Juvenile Court': 6.5,
                                                                            'Cottonwood Regional Softball Complex': 3.2,
                                                                            'Holiday City Office': 5.2,
                                                                            'Murray City Museum': 2.5,
                                                                            'Valley Regional Softball Complex': 6.0,
                                                                            'City Center of Rock Springs': 4.2,
                                                                            'Rice Terrace Pavilion Park': 5.4,
                                                                            'Wheeler Historic Farm': 5.5},
                            'South Salt Lake Public Works': {'HUB': 3.5,
                                                             'International Peace Gardens': 4.8,
                                                             'Sugar House Park': 2.8,
                                                             'Taylorsville-Bennion Heritage City Gov Off': 6.9,
                                                             'Salt Lake City Division of Health Services': 1.9,
                                                             'South Salt Lake Public Works': 0.0,
                                                             'Salt Lake City Streets and Sanitation': 6.3,
                                                             'Deker Lake': 4.3,
                                                             'Salt Lake City Ottinger Hall': 4.5,
                                                             'Columbus Library': 1.5,
                                                             'Taylorsville City Hall': 8.7,
                                                             'South Salt Lake Police': 0.8,
                                                             'Council Hall': 4.5,
                                                             'Redwood Park': 3.9,
                                                             'Salt Lake County Mental Health': 3.0,
                                                             'Salt Lake County/United Police Dept': 3.8,
                                                             'West Valley Prosecutor': 5.7,
                                                             'Housing Auth. of Salt Lake County': 1.9,
                                                             'Utah DMV Administrative Office': 1.1,
                                                             'Third District Juvenile Court': 3.5,
                                                             'Cottonwood Regional Softball Complex': 4.9,
                                                             'Holiday City Office': 6.9,
                                                             'Murray City Museum': 4.2,
                                                             'Valley Regional Softball Complex': 9.0,
                                                             'City Center of Rock Springs': 5.9,
                                                             'Rice Terrace Pavilion Park': 3.5,
                                                             'Wheeler Historic Farm': 7.2},
                            'Salt Lake City Streets and Sanitation': {'HUB': 10.9,
                                                                      'International Peace Gardens': 1.6,
                                                                      'Sugar House Park': 8.6,
                                                                      'Taylorsville-Bennion Heritage City Gov Off': 8.6,
                                                                      'Salt Lake City Division of Health Services': 7.9,
                                                                      'South Salt Lake Public Works': 6.3,
                                                                      'Salt Lake City Streets and Sanitation': 0.0,
                                                                      'Deker Lake': 4.0,
                                                                      'Salt Lake City Ottinger Hall': 4.2,
                                                                      'Columbus Library': 8.0,
                                                                      'Taylorsville City Hall': 8.6,
                                                                      'South Salt Lake Police': 6.9,
                                                                      'Council Hall': 4.2,
                                                                      'Redwood Park': 4.2,
                                                                      'Salt Lake County Mental Health': 8.0,
                                                                      'Salt Lake County/United Police Dept': 5.8,
                                                                      'West Valley Prosecutor': 7.2,
                                                                      'Housing Auth. of Salt Lake County': 7.7,
                                                                      'Utah DMV Administrative Office': 6.6,
                                                                      'Third District Juvenile Court': 3.2,
                                                                      'Cottonwood Regional Softball Complex': 11.2,
                                                                      'Holiday City Office': 12.7,
                                                                      'Murray City Museum': 10.0,
                                                                      'Valley Regional Softball Complex': 8.2,
                                                                      'City Center of Rock Springs': 11.7,
                                                                      'Rice Terrace Pavilion Park': 5.1,
                                                                      'Wheeler Historic Farm': 14.2},
                            'Deker Lake': {'HUB': 8.6,
                                           'International Peace Gardens': 2.8,
                                           'Sugar House Park': 6.3,
                                           'Taylorsville-Bennion Heritage City Gov Off': 4.0,
                                           'Salt Lake City Division of Health Services': 5.1,
                                           'South Salt Lake Public Works': 4.3,
                                           'Salt Lake City Streets and Sanitation': 4.0,
                                           'Deker Lake': 0.0,
                                           'Salt Lake City Ottinger Hall': 7.7,
                                           'Columbus Library': 9.3,
                                           'Taylorsville City Hall': 4.6,
                                           'South Salt Lake Police': 4.8,
                                           'Council Hall': 7.7,
                                           'Redwood Park': 1.6,
                                           'Salt Lake County Mental Health': 3.3,
                                           'Salt Lake County/United Police Dept': 3.4,
                                           'West Valley Prosecutor': 3.1,
                                           'Housing Auth. of Salt Lake County': 5.1,
                                           'Utah DMV Administrative Office': 4.6,
                                           'Third District Juvenile Court': 6.7,
                                           'Cottonwood Regional Softball Complex': 8.1,
                                           'Holiday City Office': 10.4,
                                           'Murray City Museum': 7.8,
                                           'Valley Regional Softball Complex': 4.2,
                                           'City Center of Rock Springs': 9.5,
                                           'Rice Terrace Pavilion Park': 6.2,
                                           'Wheeler Historic Farm': 10.7},
                            'Salt Lake City Ottinger Hall': {'HUB': 7.6,
                                                             'International Peace Gardens': 4.8,
                                                             'Sugar House Park': 5.3,
                                                             'Taylorsville-Bennion Heritage City Gov Off': 11.1,
                                                             'Salt Lake City Division of Health Services': 7.5,
                                                             'South Salt Lake Public Works': 4.5,
                                                             'Salt Lake City Streets and Sanitation': 4.2,
                                                             'Deker Lake': 7.7,
                                                             'Salt Lake City Ottinger Hall': 0.0,
                                                             'Columbus Library': 4.8,
                                                             'Taylorsville City Hall': 11.9,
                                                             'South Salt Lake Police': 4.7,
                                                             'Council Hall': 0.6,
                                                             'Redwood Park': 7.6,
                                                             'Salt Lake County Mental Health': 7.8,
                                                             'Salt Lake County/United Police Dept': 6.6,
                                                             'West Valley Prosecutor': 7.2,
                                                             'Housing Auth. of Salt Lake County': 5.9,
                                                             'Utah DMV Administrative Office': 5.4,
                                                             'Third District Juvenile Court': 1.0,
                                                             'Cottonwood Regional Softball Complex': 8.5,
                                                             'Holiday City Office': 10.3,
                                                             'Murray City Museum': 7.8,
                                                             'Valley Regional Softball Complex': 11.5,
                                                             'City Center of Rock Springs': 9.5,
                                                             'Rice Terrace Pavilion Park': 2.8,
                                                             'Wheeler Historic Farm': 14.1},
                            'Columbus Library': {'HUB': 2.8,
                                                 'International Peace Gardens': 6.3,
                                                 'Sugar House Park': 1.6,
                                                 'Taylorsville-Bennion Heritage City Gov Off': 7.3,
                                                 'Salt Lake City Division of Health Services': 2.6,
                                                 'South Salt Lake Public Works': 1.5,
                                                 'Salt Lake City Streets and Sanitation': 8.0,
                                                 'Deker Lake': 9.3,
                                                 'Salt Lake City Ottinger Hall': 4.8,
                                                 'Columbus Library': 0.0,
                                                 'Taylorsville City Hall': 9.4,
                                                 'South Salt Lake Police': 1.1,
                                                 'Council Hall': 5.1,
                                                 'Redwood Park': 4.6,
                                                 'Salt Lake County Mental Health': 3.7,
                                                 'Salt Lake County/United Police Dept': 4.0,
                                                 'West Valley Prosecutor': 6.7,
                                                 'Housing Auth. of Salt Lake County': 2.3,
                                                 'Utah DMV Administrative Office': 1.8,
                                                 'Third District Juvenile Court': 4.1,
                                                 'Cottonwood Regional Softball Complex': 3.8,
                                                 'Holiday City Office': 5.8,
                                                 'Murray City Museum': 4.3,
                                                 'Valley Regional Softball Complex': 7.8,
                                                 'City Center of Rock Springs': 4.8,
                                                 'Rice Terrace Pavilion Park': 3.2,
                                                 'Wheeler Historic Farm': 6.0},
                            'Taylorsville City Hall': {'HUB': 6.4,
                                                       'International Peace Gardens': 7.3,
                                                       'Sugar House Park': 10.4,
                                                       'Taylorsville-Bennion Heritage City Gov Off': 1.0,
                                                       'Salt Lake City Division of Health Services': 6.5,
                                                       'South Salt Lake Public Works': 8.7,
                                                       'Salt Lake City Streets and Sanitation': 8.6,
                                                       'Deker Lake': 4.6,
                                                       'Salt Lake City Ottinger Hall': 11.9,
                                                       'Columbus Library': 9.4,
                                                       'Taylorsville City Hall': 0.0,
                                                       'South Salt Lake Police': 7.3,
                                                       'Council Hall': 12.0,
                                                       'Redwood Park': 4.9,
                                                       'Salt Lake County Mental Health': 5.2,
                                                       'Salt Lake County/United Police Dept': 5.4,
                                                       'West Valley Prosecutor': 8.1,
                                                       'Housing Auth. of Salt Lake County': 6.2,
                                                       'Utah DMV Administrative Office': 6.9,
                                                       'Third District Juvenile Court': 11.5,
                                                       'Cottonwood Regional Softball Complex': 6.9,
                                                       'Holiday City Office': 8.3,
                                                       'Murray City Museum': 4.1,
                                                       'Valley Regional Softball Complex': 0.4,
                                                       'City Center of Rock Springs': 4.9,
                                                       'Rice Terrace Pavilion Park': 11.0,
                                                       'Wheeler Historic Farm': 6.8},
                            'South Salt Lake Police': {'HUB': 3.2,
                                                       'International Peace Gardens': 5.3,
                                                       'Sugar House Park': 3.0,
                                                       'Taylorsville-Bennion Heritage City Gov Off': 6.4,
                                                       'Salt Lake City Division of Health Services': 1.5,
                                                       'South Salt Lake Public Works': 0.8,
                                                       'Salt Lake City Streets and Sanitation': 6.9,
                                                       'Deker Lake': 4.8,
                                                       'Salt Lake City Ottinger Hall': 4.7,
                                                       'Columbus Library': 1.1,
                                                       'Taylorsville City Hall': 7.3,
                                                       'South Salt Lake Police': 0.0,
                                                       'Council Hall': 4.7,
                                                       'Redwood Park': 3.5,
                                                       'Salt Lake County Mental Health': 2.6,
                                                       'Salt Lake County/United Police Dept': 2.9,
                                                       'West Valley Prosecutor': 6.3,
                                                       'Housing Auth. of Salt Lake County': 1.2,
                                                       'Utah DMV Administrative Office': 1.0,
                                                       'Third District Juvenile Court': 3.7,
                                                       'Cottonwood Regional Softball Complex': 4.1,
                                                       'Holiday City Office': 6.2,
                                                       'Murray City Museum': 3.4,
                                                       'Valley Regional Softball Complex': 6.9,
                                                       'City Center of Rock Springs': 5.2,
                                                       'Rice Terrace Pavilion Park': 3.7,
                                                       'Wheeler Historic Farm': 6.4},
                            'Council Hall': {'HUB': 7.6,
                                             'International Peace Gardens': 4.8,
                                             'Sugar House Park': 5.3,
                                             'Taylorsville-Bennion Heritage City Gov Off': 11.1,
                                             'Salt Lake City Division of Health Services': 7.5,
                                             'South Salt Lake Public Works': 4.5,
                                             'Salt Lake City Streets and Sanitation': 4.2,
                                             'Deker Lake': 7.7,
                                             'Salt Lake City Ottinger Hall': 0.6,
                                             'Columbus Library': 5.1,
                                             'Taylorsville City Hall': 12.0,
                                             'South Salt Lake Police': 4.7,
                                             'Council Hall': 0.0,
                                             'Redwood Park': 7.3,
                                             'Salt Lake County Mental Health': 7.8,
                                             'Salt Lake County/United Police Dept': 6.6,
                                             'West Valley Prosecutor': 7.2,
                                             'Housing Auth. of Salt Lake County': 5.9,
                                             'Utah DMV Administrative Office': 5.4,
                                             'Third District Juvenile Court': 1.0,
                                             'Cottonwood Regional Softball Complex': 8.5,
                                             'Holiday City Office': 10.3,
                                             'Murray City Museum': 7.8,
                                             'Valley Regional Softball Complex': 11.5,
                                             'City Center of Rock Springs': 9.5,
                                             'Rice Terrace Pavilion Park': 2.8,
                                             'Wheeler Historic Farm': 14.1},
                            'Redwood Park': {'HUB': 5.2,
                                             'International Peace Gardens': 3.0,
                                             'Sugar House Park': 6.5,
                                             'Taylorsville-Bennion Heritage City Gov Off': 3.9,
                                             'Salt Lake City Division of Health Services': 3.2,
                                             'South Salt Lake Public Works': 3.9,
                                             'Salt Lake City Streets and Sanitation': 4.2,
                                             'Deker Lake': 1.6,
                                             'Salt Lake City Ottinger Hall': 7.6,
                                             'Columbus Library': 4.6,
                                             'Taylorsville City Hall': 4.9,
                                             'South Salt Lake Police': 3.5,
                                             'Council Hall': 7.3,
                                             'Redwood Park': 0.0,
                                             'Salt Lake County Mental Health': 1.3,
                                             'Salt Lake County/United Police Dept': 1.5,
                                             'West Valley Prosecutor': 4.0,
                                             'Housing Auth. of Salt Lake County': 3.2,
                                             'Utah DMV Administrative Office': 3.0,
                                             'Third District Juvenile Court': 6.9,
                                             'Cottonwood Regional Softball Complex': 6.2,
                                             'Holiday City Office': 8.2,
                                             'Murray City Museum': 5.5,
                                             'Valley Regional Softball Complex': 4.4,
                                             'City Center of Rock Springs': 7.2,
                                             'Rice Terrace Pavilion Park': 6.4,
                                             'Wheeler Historic Farm': 10.5},
                            'Salt Lake County Mental Health': {'HUB': 4.4,
                                                               'International Peace Gardens': 4.6,
                                                               'Sugar House Park': 5.6,
                                                               'Taylorsville-Bennion Heritage City Gov Off': 4.3,
                                                               'Salt Lake City Division of Health Services': 2.4,
                                                               'South Salt Lake Public Works': 3.0,
                                                               'Salt Lake City Streets and Sanitation': 8.0,
                                                               'Deker Lake': 3.3,
                                                               'Salt Lake City Ottinger Hall': 7.8,
                                                               'Columbus Library': 3.7,
                                                               'Taylorsville City Hall': 5.2,
                                                               'South Salt Lake Police': 2.6,
                                                               'Council Hall': 7.8,
                                                               'Redwood Park': 1.3,
                                                               'Salt Lake County Mental Health': 0.0,
                                                               'Salt Lake County/United Police Dept': 0.6,
                                                               'West Valley Prosecutor': 6.4,
                                                               'Housing Auth. of Salt Lake County': 2.4,
                                                               'Utah DMV Administrative Office': 2.2,
                                                               'Third District Juvenile Court': 6.8,
                                                               'Cottonwood Regional Softball Complex': 5.3,
                                                               'Holiday City Office': 7.4,
                                                               'Murray City Museum': 4.6,
                                                               'Valley Regional Softball Complex': 4.8,
                                                               'City Center of Rock Springs': 6.3,
                                                               'Rice Terrace Pavilion Park': 6.5,
                                                               'Wheeler Historic Farm': 8.8},
                            'Salt Lake County/United Police Dept': {'HUB': 3.7,
                                                                    'International Peace Gardens': 4.5,
                                                                    'Sugar House Park': 5.8,
                                                                    'Taylorsville-Bennion Heritage City Gov Off': 4.4,
                                                                    'Salt Lake City Division of Health Services': 2.7,
                                                                    'South Salt Lake Public Works': 3.8,
                                                                    'Salt Lake City Streets and Sanitation': 5.8,
                                                                    'Deker Lake': 3.4,
                                                                    'Salt Lake City Ottinger Hall': 6.6,
                                                                    'Columbus Library': 4.0,
                                                                    'Taylorsville City Hall': 5.4,
                                                                    'South Salt Lake Police': 2.9,
                                                                    'Council Hall': 6.6,
                                                                    'Redwood Park': 1.5,
                                                                    'Salt Lake County Mental Health': 0.6,
                                                                    'Salt Lake County/United Police Dept': 0.0,
                                                                    'West Valley Prosecutor': 5.6,
                                                                    'Housing Auth. of Salt Lake County': 1.6,
                                                                    'Utah DMV Administrative Office': 1.7,
                                                                    'Third District Juvenile Court': 6.4,
                                                                    'Cottonwood Regional Softball Complex': 4.9,
                                                                    'Holiday City Office': 6.9,
                                                                    'Murray City Museum': 4.2,
                                                                    'Valley Regional Softball Complex': 5.6,
                                                                    'City Center of Rock Springs': 5.9,
                                                                    'Rice Terrace Pavilion Park': 5.7,
                                                                    'Wheeler Historic Farm': 8.4},
                            'West Valley Prosecutor': {'HUB': 7.6,
                                                       'International Peace Gardens': 7.4,
                                                       'Sugar House Park': 5.7,
                                                       'Taylorsville-Bennion Heritage City Gov Off': 7.2,
                                                       'Salt Lake City Division of Health Services': 1.4,
                                                       'South Salt Lake Public Works': 5.7,
                                                       'Salt Lake City Streets and Sanitation': 7.2,
                                                       'Deker Lake': 3.1,
                                                       'Salt Lake City Ottinger Hall': 7.2,
                                                       'Columbus Library': 6.7,
                                                       'Taylorsville City Hall': 8.1,
                                                       'South Salt Lake Police': 6.3,
                                                       'Council Hall': 7.2,
                                                       'Redwood Park': 4.0,
                                                       'Salt Lake County Mental Health': 6.4,
                                                       'Salt Lake County/United Police Dept': 5.6,
                                                       'West Valley Prosecutor': 0.0,
                                                       'Housing Auth. of Salt Lake County': 7.1,
                                                       'Utah DMV Administrative Office': 6.1,
                                                       'Third District Juvenile Court': 7.2,
                                                       'Cottonwood Regional Softball Complex': 10.6,
                                                       'Holiday City Office': 12.0,
                                                       'Murray City Museum': 9.4,
                                                       'Valley Regional Softball Complex': 7.5,
                                                       'City Center of Rock Springs': 11.1,
                                                       'Rice Terrace Pavilion Park': 6.2,
                                                       'Wheeler Historic Farm': 13.6},
                            'Housing Auth. of Salt Lake County': {'HUB': 2.0,
                                                                  'International Peace Gardens': 6.0,
                                                                  'Sugar House Park': 4.1,
                                                                  'Taylorsville-Bennion Heritage City Gov Off': 5.3,
                                                                  'Salt Lake City Division of Health Services': 0.5,
                                                                  'South Salt Lake Public Works': 1.9,
                                                                  'Salt Lake City Streets and Sanitation': 7.7,
                                                                  'Deker Lake': 5.1,
                                                                  'Salt Lake City Ottinger Hall': 5.9,
                                                                  'Columbus Library': 2.3,
                                                                  'Taylorsville City Hall': 6.2,
                                                                  'South Salt Lake Police': 1.2,
                                                                  'Council Hall': 5.9,
                                                                  'Redwood Park': 3.2,
                                                                  'Salt Lake County Mental Health': 2.4,
                                                                  'Salt Lake County/United Police Dept': 1.6,
                                                                  'West Valley Prosecutor': 7.1,
                                                                  'Housing Auth. of Salt Lake County': 0.0,
                                                                  'Utah DMV Administrative Office': 1.6,
                                                                  'Third District Juvenile Court': 4.9,
                                                                  'Cottonwood Regional Softball Complex': 3.0,
                                                                  'Holiday City Office': 5.0,
                                                                  'Murray City Museum': 2.3,
                                                                  'Valley Regional Softball Complex': 5.5,
                                                                  'City Center of Rock Springs': 4.0,
                                                                  'Rice Terrace Pavilion Park': 5.1,
                                                                  'Wheeler Historic Farm': 5.2},
                            'Utah DMV Administrative Office': {'HUB': 3.6,
                                                               'International Peace Gardens': 5.0,
                                                               'Sugar House Park': 3.6,
                                                               'Taylorsville-Bennion Heritage City Gov Off': 6.0,
                                                               'Salt Lake City Division of Health Services': 1.7,
                                                               'South Salt Lake Public Works': 1.1,
                                                               'Salt Lake City Streets and Sanitation': 6.6,
                                                               'Deker Lake': 4.6,
                                                               'Salt Lake City Ottinger Hall': 5.4,
                                                               'Columbus Library': 1.8,
                                                               'Taylorsville City Hall': 6.9,
                                                               'South Salt Lake Police': 1.0,
                                                               'Council Hall': 5.4,
                                                               'Redwood Park': 3.0,
                                                               'Salt Lake County Mental Health': 2.2,
                                                               'Salt Lake County/United Police Dept': 1.7,
                                                               'West Valley Prosecutor': 6.1,
                                                               'Housing Auth. of Salt Lake County': 1.6,
                                                               'Utah DMV Administrative Office': 0.0,
                                                               'Third District Juvenile Court': 4.4,
                                                               'Cottonwood Regional Softball Complex': 4.6,
                                                               'Holiday City Office': 6.6,
                                                               'Murray City Museum': 3.9,
                                                               'Valley Regional Softball Complex': 6.5,
                                                               'City Center of Rock Springs': 5.6,
                                                               'Rice Terrace Pavilion Park': 4.3,
                                                               'Wheeler Historic Farm': 6.9},
                            'Third District Juvenile Court': {'HUB': 6.5,
                                                              'International Peace Gardens': 4.8,
                                                              'Sugar House Park': 4.3,
                                                              'Taylorsville-Bennion Heritage City Gov Off': 10.6,
                                                              'Salt Lake City Division of Health Services': 6.5,
                                                              'South Salt Lake Public Works': 3.5,
                                                              'Salt Lake City Streets and Sanitation': 3.2,
                                                              'Deker Lake': 6.7,
                                                              'Salt Lake City Ottinger Hall': 1.0,
                                                              'Columbus Library': 4.1,
                                                              'Taylorsville City Hall': 11.5,
                                                              'South Salt Lake Police': 3.7,
                                                              'Council Hall': 1.0,
                                                              'Redwood Park': 6.9,
                                                              'Salt Lake County Mental Health': 6.8,
                                                              'Salt Lake County/United Police Dept': 6.4,
                                                              'West Valley Prosecutor': 7.2,
                                                              'Housing Auth. of Salt Lake County': 4.9,
                                                              'Utah DMV Administrative Office': 4.4,
                                                              'Third District Juvenile Court': 0.0,
                                                              'Cottonwood Regional Softball Complex': 7.5,
                                                              'Holiday City Office': 9.3,
                                                              'Murray City Museum': 6.8,
                                                              'Valley Regional Softball Complex': 11.4,
                                                              'City Center of Rock Springs': 8.5,
                                                              'Rice Terrace Pavilion Park': 1.8,
                                                              'Wheeler Historic Farm': 13.1},
                            'Cottonwood Regional Softball Complex': {'HUB': 1.9,
                                                                     'International Peace Gardens': 9.5,
                                                                     'Sugar House Park': 3.3,
                                                                     'Taylorsville-Bennion Heritage City Gov Off': 5.9,
                                                                     'Salt Lake City Division of Health Services': 3.2,
                                                                     'South Salt Lake Public Works': 4.9,
                                                                     'Salt Lake City Streets and Sanitation': 11.2,
                                                                     'Deker Lake': 8.1,
                                                                     'Salt Lake City Ottinger Hall': 8.5,
                                                                     'Columbus Library': 3.8,
                                                                     'Taylorsville City Hall': 6.9,
                                                                     'South Salt Lake Police': 4.1,
                                                                     'Council Hall': 8.5,
                                                                     'Redwood Park': 6.2,
                                                                     'Salt Lake County Mental Health': 5.3,
                                                                     'Salt Lake County/United Police Dept': 4.9,
                                                                     'West Valley Prosecutor': 10.6,
                                                                     'Housing Auth. of Salt Lake County': 3.0,
                                                                     'Utah DMV Administrative Office': 4.6,
                                                                     'Third District Juvenile Court': 7.5,
                                                                     'Cottonwood Regional Softball Complex': 0.0,
                                                                     'Holiday City Office': 2.0,
                                                                     'Murray City Museum': 2.9,
                                                                     'Valley Regional Softball Complex': 6.4,
                                                                     'City Center of Rock Springs': 2.8,
                                                                     'Rice Terrace Pavilion Park': 6.0,
                                                                     'Wheeler Historic Farm': 4.1},
                            'Holiday City Office': {'HUB': 3.4,
                                                    'International Peace Gardens': 10.9,
                                                    'Sugar House Park': 5.0,
                                                    'Taylorsville-Bennion Heritage City Gov Off': 7.4,
                                                    'Salt Lake City Division of Health Services': 5.2,
                                                    'South Salt Lake Public Works': 6.9,
                                                    'Salt Lake City Streets and Sanitation': 12.7,
                                                    'Deker Lake': 10.4,
                                                    'Salt Lake City Ottinger Hall': 10.3,
                                                    'Columbus Library': 5.8,
                                                    'Taylorsville City Hall': 8.3,
                                                    'South Salt Lake Police': 6.2,
                                                    'Council Hall': 10.3,
                                                    'Redwood Park': 8.2,
                                                    'Salt Lake County Mental Health': 7.4,
                                                    'Salt Lake County/United Police Dept': 6.9,
                                                    'West Valley Prosecutor': 12.0,
                                                    'Housing Auth. of Salt Lake County': 5.0,
                                                    'Utah DMV Administrative Office': 6.6,
                                                    'Third District Juvenile Court': 9.3,
                                                    'Cottonwood Regional Softball Complex': 2.0,
                                                    'Holiday City Office': 0.0,
                                                    'Murray City Museum': 4.4,
                                                    'Valley Regional Softball Complex': 7.9,
                                                    'City Center of Rock Springs': 3.4,
                                                    'Rice Terrace Pavilion Park': 7.9,
                                                    'Wheeler Historic Farm': 4.7},
                            'Murray City Museum': {'HUB': 2.4,
                                                   'International Peace Gardens': 8.3,
                                                   'Sugar House Park': 6.1,
                                                   'Taylorsville-Bennion Heritage City Gov Off': 4.7,
                                                   'Salt Lake City Division of Health Services': 2.5,
                                                   'South Salt Lake Public Works': 4.2,
                                                   'Salt Lake City Streets and Sanitation': 10.0,
                                                   'Deker Lake': 7.8,
                                                   'Salt Lake City Ottinger Hall': 7.8,
                                                   'Columbus Library': 4.3,
                                                   'Taylorsville City Hall': 4.1,
                                                   'South Salt Lake Police': 3.4,
                                                   'Council Hall': 7.8,
                                                   'Redwood Park': 5.5,
                                                   'Salt Lake County Mental Health': 4.6,
                                                   'Salt Lake County/United Police Dept': 4.2,
                                                   'West Valley Prosecutor': 9.4,
                                                   'Housing Auth. of Salt Lake County': 2.3,
                                                   'Utah DMV Administrative Office': 3.9,
                                                   'Third District Juvenile Court': 6.8,
                                                   'Cottonwood Regional Softball Complex': 2.9,
                                                   'Holiday City Office': 4.4,
                                                   'Murray City Museum': 0.0,
                                                   'Valley Regional Softball Complex': 4.5,
                                                   'City Center of Rock Springs': 1.7,
                                                   'Rice Terrace Pavilion Park': 6.8,
                                                   'Wheeler Historic Farm': 3.1},
                            'Valley Regional Softball Complex': {'HUB': 6.4,
                                                                 'International Peace Gardens': 6.9,
                                                                 'Sugar House Park': 9.7,
                                                                 'Taylorsville-Bennion Heritage City Gov Off': 0.6,
                                                                 'Salt Lake City Division of Health Services': 6.0,
                                                                 'South Salt Lake Public Works': 9.0,
                                                                 'Salt Lake City Streets and Sanitation': 8.2,
                                                                 'Deker Lake': 4.2,
                                                                 'Salt Lake City Ottinger Hall': 11.5,
                                                                 'Columbus Library': 7.8,
                                                                 'Taylorsville City Hall': 0.4,
                                                                 'South Salt Lake Police': 6.9,
                                                                 'Council Hall': 11.5,
                                                                 'Redwood Park': 4.4,
                                                                 'Salt Lake County Mental Health': 4.8,
                                                                 'Salt Lake County/United Police Dept': 5.6,
                                                                 'West Valley Prosecutor': 7.5,
                                                                 'Housing Auth. of Salt Lake County': 5.5,
                                                                 'Utah DMV Administrative Office': 6.5,
                                                                 'Third District Juvenile Court': 11.4,
                                                                 'Cottonwood Regional Softball Complex': 6.4,
                                                                 'Holiday City Office': 7.9,
                                                                 'Murray City Museum': 4.5,
                                                                 'Valley Regional Softball Complex': 0.0,
                                                                 'City Center of Rock Springs': 5.4,
                                                                 'Rice Terrace Pavilion Park': 10.6,
                                                                 'Wheeler Historic Farm': 7.8},
                            'City Center of Rock Springs': {'HUB': 2.4,
                                                            'International Peace Gardens': 10.0,
                                                            'Sugar House Park': 6.1,
                                                            'Taylorsville-Bennion Heritage City Gov Off': 6.4,
                                                            'Salt Lake City Division of Health Services': 4.2,
                                                            'South Salt Lake Public Works': 5.9,
                                                            'Salt Lake City Streets and Sanitation': 11.7,
                                                            'Deker Lake': 9.5,
                                                            'Salt Lake City Ottinger Hall': 9.5,
                                                            'Columbus Library': 4.8,
                                                            'Taylorsville City Hall': 4.9,
                                                            'South Salt Lake Police': 5.2,
                                                            'Council Hall': 9.5,
                                                            'Redwood Park': 7.2,
                                                            'Salt Lake County Mental Health': 6.3,
                                                            'Salt Lake County/United Police Dept': 5.9,
                                                            'West Valley Prosecutor': 11.1,
                                                            'Housing Auth. of Salt Lake County': 4.0,
                                                            'Utah DMV Administrative Office': 5.6,
                                                            'Third District Juvenile Court': 8.5,
                                                            'Cottonwood Regional Softball Complex': 2.8,
                                                            'Holiday City Office': 3.4,
                                                            'Murray City Museum': 1.7,
                                                            'Valley Regional Softball Complex': 5.4,
                                                            'City Center of Rock Springs': 0.0,
                                                            'Rice Terrace Pavilion Park': 7.0,
                                                            'Wheeler Historic Farm': 1.3},
                            'Rice Terrace Pavilion Park': {'HUB': 5.0,
                                                           'International Peace Gardens': 4.4,
                                                           'Sugar House Park': 2.8,
                                                           'Taylorsville-Bennion Heritage City Gov Off': 10.1,
                                                           'Salt Lake City Division of Health Services': 5.4,
                                                           'South Salt Lake Public Works': 3.5,
                                                           'Salt Lake City Streets and Sanitation': 5.1,
                                                           'Deker Lake': 6.2,
                                                           'Salt Lake City Ottinger Hall': 2.8,
                                                           'Columbus Library': 3.2,
                                                           'Taylorsville City Hall': 11.0,
                                                           'South Salt Lake Police': 3.7,
                                                           'Council Hall': 2.8,
                                                           'Redwood Park': 6.4,
                                                           'Salt Lake County Mental Health': 6.5,
                                                           'Salt Lake County/United Police Dept': 5.7,
                                                           'West Valley Prosecutor': 6.2,
                                                           'Housing Auth. of Salt Lake County': 5.1,
                                                           'Utah DMV Administrative Office': 4.3,
                                                           'Third District Juvenile Court': 1.8,
                                                           'Cottonwood Regional Softball Complex': 6.0,
                                                           'Holiday City Office': 7.9,
                                                           'Murray City Museum': 6.8,
                                                           'Valley Regional Softball Complex': 10.6,
                                                           'City Center of Rock Springs': 7.0,
                                                           'Rice Terrace Pavilion Park': 0.0,
                                                           'Wheeler Historic Farm': 8.3},
                            'Wheeler Historic Farm': {'HUB': 3.6,
                                                      'International Peace Gardens': 13.0,
                                                      'Sugar House Park': 7.4,
                                                      'Taylorsville-Bennion Heritage City Gov Off': 10.1,
                                                      'Salt Lake City Division of Health Services': 5.5,
                                                      'South Salt Lake Public Works': 7.2,
                                                      'Salt Lake City Streets and Sanitation': 14.2,
                                                      'Deker Lake': 10.7,
                                                      'Salt Lake City Ottinger Hall': 14.1,
                                                      'Columbus Library': 6.0,
                                                      'Taylorsville City Hall': 6.8,
                                                      'South Salt Lake Police': 6.4,
                                                      'Council Hall': 14.1,
                                                      'Redwood Park': 10.5,
                                                      'Salt Lake County Mental Health': 8.8,
                                                      'Salt Lake County/United Police Dept': 8.4,
                                                      'West Valley Prosecutor': 13.6,
                                                      'Housing Auth. of Salt Lake County': 5.2,
                                                      'Utah DMV Administrative Office': 6.9,
                                                      'Third District Juvenile Court': 13.1,
                                                      'Cottonwood Regional Softball Complex': 4.1,
                                                      'Holiday City Office': 4.7,
                                                      'Murray City Museum': 3.1,
                                                      'Valley Regional Softball Complex': 7.8,
                                                      'City Center of Rock Springs': 1.3,
                                                      'Rice Terrace Pavilion Park': 8.3,
                                                      'Wheeler Historic Farm': 0.0}
                            }


        self.address_to_place={"4001 South 700 East" : "HUB",
                  "1060 Dalton Ave S" : "International Peace Gardens",
                  "1330 2100 S" : "Sugar House Park",
                  "1488 4800 S" : "Taylorsville-Bennion Heritage City Gov Off",
                  "177 W Price Ave" : "Salt Lake City Division of Health Services",
                  "195 W Oakland Ave" : "South Salt Lake Public Works",
                  "2010 W 500 S" : "Salt Lake City Streets and Sanitation",
                  "2300 Parkway Blvd" : "Deker Lake",
                  "233 Canyon Rd" : "Salt Lake City Ottinger Hall",
                  "2530 S 500 E" : "Columbus Library",
                  "2600 Taylorsville Blvd" : "Taylorsville City Hall",
                  "2835 Main St" : "South Salt Lake Police",
                  "300 State St" : "Council Hall",
                  "3060 Lester St" : "Redwood Park",
                  "3148 S 1100 W" : "Salt Lake County Mental Health",
                  "3365 S 900 W" : "Salt Lake County/United Police Dept",
                  "3575 W Valley Central Station bus Loop" : "West Valley Prosecutor",
                  "3595 Main St" : "Housing Auth. of Salt Lake County",
                  "380 W 2880 S" : "Utah DMV Administrative Office",
                  "410 S State St" : "Third District Juvenile Court",
                  "4300 S 1300 E" : "Cottonwood Regional Softball Complex",
                  "4580 S 2300 E" : "Holiday City Office",
                  "5025 State St" : "Murray City Museum",
                  "5100 South 2700 West" : "Valley Regional Softball Complex",
                  "5383 South 900 East #104" : "City Center of Rock Springs",
                  "600 E 900 South" : "Rice Terrace Pavilion Park",
                  "6351 South 900 East" : "Wheeler Historic Farm"
                  }
